// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFMZUBnp_erdxeltYaQjkhJMlauIstmow',
    appId: '1:508124749678:web:cd4fb0808f34fa2ffe2b7f',
    messagingSenderId: '508124749678',
    projectId: 'anerastaner',
    authDomain: 'anerastaner.firebaseapp.com',
    storageBucket: 'anerastaner.firebasestorage.app',
    measurementId: 'G-2BMNRHN8RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANL3iSHXSZzOFdabUS-PaT9miSYrtmc9s',
    appId: '1:508124749678:android:9562b3ef4499f326fe2b7f',
    messagingSenderId: '508124749678',
    projectId: 'anerastaner',
    storageBucket: 'anerastaner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMtNELGJQZ8_n6v3lJ1E8ZlACAaKe70HE',
    appId: '1:508124749678:ios:1da510abd9d92fdcfe2b7f',
    messagingSenderId: '508124749678',
    projectId: 'anerastaner',
    storageBucket: 'anerastaner.firebasestorage.app',
    iosBundleId: 'com.example.anerAstaner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMtNELGJQZ8_n6v3lJ1E8ZlACAaKe70HE',
    appId: '1:508124749678:ios:1da510abd9d92fdcfe2b7f',
    messagingSenderId: '508124749678',
    projectId: 'anerastaner',
    storageBucket: 'anerastaner.firebasestorage.app',
    iosBundleId: 'com.example.anerAstaner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFMZUBnp_erdxeltYaQjkhJMlauIstmow',
    appId: '1:508124749678:web:0960823f10ef49a7fe2b7f',
    messagingSenderId: '508124749678',
    projectId: 'anerastaner',
    authDomain: 'anerastaner.firebaseapp.com',
    storageBucket: 'anerastaner.firebasestorage.app',
    measurementId: 'G-HQW4STKXLB',
  );

}